# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM python:3.10-slim

WORKDIR /app

# Install dependencies
COPY . /app
RUN pip install --no-cache-dir fastapi uvicorn openai mcp requests filetype aiofiles

# Expose storage server port (internal use)
EXPOSE 9000

# Default command to start MCP server over stdio
CMD ["python", "openai_image.py"]
